### ISSUE TITLE
why can't install ?

### ISSUE THREAD

**Issue by T0mbery** [pybee/seasnake#7]
~/... $ pip install seasnake

Collecting seasnake
  Could not find a version that satisfies the requirement seasnake (from versions: )
No matching distribution found for seasnake

what it can be?

**Comment by freakboy3742** [comment]
If you check PyPI, you'll see that the "current version" is 0.0.0 - That is, I never uploaded a version to PyPI. 

This project was an experiment; I've since abandoned the experiment, so you'll need to use a checkout of the code.
